DROP INDEX IF EXISTS analytics.hashed_passenger_passport_id;
DROP INDEX IF EXISTS analytics.hashed_notes_in_luggage_inspection;
DROP INDEX IF EXISTS analytics.hashed_item_count_in_luggage_inspection;
DROP INDEX IF EXISTS analytics.hashed_screening_score_in_criminal_screening;
DROP INDEX IF EXISTS analytics.hashed_transport_type_in_border_crossing;