GRANT USAGE ON SCHEMA public TO app, readonly;

GRANT SELECT, INSERT, UPDATE, DELETE 
ON ALL TABLES IN SCHEMA public TO app;

GRANT SELECT
ON ALL TABLES IN SCHEMA public TO readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO app;

ALTER DEFAULT PRIVILEGES 
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO app;

ALTER DEFAULT PRIVILEGES 
IN SCHEMA public
GRANT SELECT
ON TABLES TO readonly;