GRANT USAGE ON SCHEMA analytics TO app, readonly;

GRANT SELECT, INSERT, UPDATE, DELETE 
ON ALL TABLES IN SCHEMA analytics TO app;

GRANT SELECT
ON ALL TABLES IN SCHEMA analytics TO readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA analytics TO app;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA analytics TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA analytics
GRANT USAGE, SELECT ON SEQUENCES TO app;

ALTER DEFAULT PRIVILEGES 
IN SCHEMA analytics
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO app;

ALTER DEFAULT PRIVILEGES 
IN SCHEMA analytics
GRANT SELECT
ON TABLES TO readonly;