version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_course
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: postgres 17
      POSTGRES_PASSWORD: gr00sha207
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    command: 
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./db/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/course_db
      FLYWAY_USER: postgres 17
      FLYWAY_PASSWORD: gr00sha207
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: public 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: daniargarafiev6@gmail.com
      PGADMIN_DEFAULT_PASSWORD: gr00sha207
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data: